### PR TITLE
Dynamically generate code using build script, and using the recursive…

### PR DESCRIPTION
**Pull request by novacrazy**
… macro method described in https://gist.github.com/DanielKeep/8b622db9f9c246cbea4a8f469003cdc8

I just saw you took the python version, but I rewrote it in Rust using a build script, and allow the maximum limit to be set with a cargo feature.

### CODE REVIEW

**Comment by novacrazy** [comment]
I merged the upstream (yours) into mine so it's easier to accept this pull request.

**Comment by Vurich** [comment]
Hey, thanks a lot! This is exactly how I wanted to implement this but was too lazy. I've got a couple notes, but otherwise this is ready to go in.

Firstly, I don't really like the reuse of the name `limit`, just use `i` or give the loop variable a better name (although `i` is fine here). Also, I'd prefer if the default limit was 128, but that's not a big thing.

**Comment by novacrazy** [comment]
Fixed the double limit thing. I set the default feature limit to the lowest because I think cargo always includes the default features unless explicitly told not to, so including a large limit by default would make it more annoying to specify smaller limits, but still easy to specify higher ones.

**Comment by novacrazy** [comment]
I went ahead and added some documentation to it rather than leaving it empty.

**Comment by novacrazy** [comment]
Any further thoughts on this?

**Comment by Vurich** [comment]
This is a really quality PR, thanks for submitting. The docs currently don't mention the loop variable being converted into a constant (and so the example unrolled code is wrong) but I'll merge this and then just commit that myself.

**Comment by novacrazy** [comment]
Let me know when you publish a new version to crates.io. Although you might want to bump to 0.2.0 given the cargo feature changes.

**Comment by Vurich** [comment]
Sure.

**Pull request merged**
